# Data Preprocess

In [33]:
import pandas as pd
import numpy as np

In [43]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("abcbbong/brewery-csv")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version, please consider updating (latest version: 0.3.11)
Path to dataset files: /Users/isaacadoboe/.cache/kagglehub/datasets/abcbbong/brewery-csv/versions/1

In [55]:
df = pd.read_csv("/Users/isaacadoboe/.cache/kagglehub/datasets/abcbbong/brewery-csv/versions/1/brewery_data_complete_extended.csv")
df.tail()

,Batch_ID,Brew_Date,Beer_Style,SKU,Location,Fermentation_Time,Temperature,pH_Level,Gravity,Alcohol_Content,Bitterness,Color,Ingredient_Ratio,Volume_Produced,Total_Sales,Quality_Score,Brewhouse_Efficiency,Loss_During_Brewing,Loss_During_Fermentation,Loss_During_Bottling_Kegging
9999995,4575645,2023-12-31 23:58:59,Stout,Bottles,Yelahanka,12,20.719151,4.944343,1.049876,5.437139,28,15,1:0.31:0.17,3054,6655.673836,6.264104,79.654815,4.612468,1.484389,1.118612
9999996,2074362,2023-12-31 23:59:18,Wheat Beer,Bottles,Electronic City,19,16.970908,5.121963,1.037019,5.102428,47,6,1:0.30:0.19,1985,10440.357817,9.651172,89.119201,2.112756,1.150946,4.972988
9999997,177617,2023-12-31 23:59:41,IPA,Bottles,Malleswaram,10,24.386184,4.747588,1.047490,5.025251,24,6,1:0.43:0.14,1982,17069.572855,9.060614,72.555455,3.393856,3.011241,2.115054
9999998,7306891,2023-12-31 23:59:45,Ale,Kegs,Electronic City,18,18.056172,5.007909,1.046138,5.843181,58,17,1:0.41:0.25,4016,5316.412808,6.297562,87.650899,4.095874,4.711502,1.535620
9999999,5072143,2023-12-31 23:59:54,Wheat Beer,Pints,Electronic City,11,22.195310,4.883125,1.074231,5.307453,20,17,1:0.41:0.27,3948,8235.956266,8.109398,79.833365,3.471192,1.764435,3.536902

In [56]:
df.shape

(10000000, 20)

In [57]:
filtered_df = df[df.SKU == "Bottles"]
filtered_df.tail()

,Batch_ID,Brew_Date,Beer_Style,SKU,Location,Fermentation_Time,Temperature,pH_Level,Gravity,Alcohol_Content,Bitterness,Color,Ingredient_Ratio,Volume_Produced,Total_Sales,Quality_Score,Brewhouse_Efficiency,Loss_During_Brewing,Loss_During_Fermentation,Loss_During_Bottling_Kegging
9999990,4874627,2023-12-31 23:57:56,Wheat Beer,Bottles,Rajajinagar,17,21.292334,4.592902,1.073923,5.455494,30,8,1:0.45:0.28,2367,15780.989273,6.632373,74.190511,1.925121,3.420429,2.113684
9999991,4797863,2023-12-31 23:58:02,Sour,Bottles,Malleswaram,17,19.852307,5.486420,1.073821,5.771123,30,9,1:0.31:0.19,3506,19877.989207,7.751034,88.615632,4.444804,1.236727,4.171654
9999995,4575645,2023-12-31 23:58:59,Stout,Bottles,Yelahanka,12,20.719151,4.944343,1.049876,5.437139,28,15,1:0.31:0.17,3054,6655.673836,6.264104,79.654815,4.612468,1.484389,1.118612
9999996,2074362,2023-12-31 23:59:18,Wheat Beer,Bottles,Electronic City,19,16.970908,5.121963,1.037019,5.102428,47,6,1:0.30:0.19,1985,10440.357817,9.651172,89.119201,2.112756,1.150946,4.972988
9999997,177617,2023-12-31 23:59:41,IPA,Bottles,Malleswaram,10,24.386184,4.747588,1.047490,5.025251,24,6,1:0.43:0.14,1982,17069.572855,9.060614,72.555455,3.393856,3.011241,2.115054

In [58]:
dataset = filtered_df.sample(1000, replace=False)

In [59]:
dataset.shape

(1000, 20)

In [60]:
dataset.columns

Index(['Batch_ID', 'Brew_Date', 'Beer_Style', 'SKU', 'Location',
       'Fermentation_Time', 'Temperature', 'pH_Level', 'Gravity',
       'Alcohol_Content', 'Bitterness', 'Color', 'Ingredient_Ratio',
       'Volume_Produced', 'Total_Sales', 'Quality_Score',
       'Brewhouse_Efficiency', 'Loss_During_Brewing',
       'Loss_During_Fermentation', 'Loss_During_Bottling_Kegging'],
      dtype='object')

In [61]:
dataset = dataset.drop(columns=['Batch_ID', 'Brew_Date', 'SKU', 'Color', 'Ingredient_Ratio'])

In [62]:
dataset.tail()

,Beer_Style,Location,Fermentation_Time,Temperature,pH_Level,Gravity,Alcohol_Content,Bitterness,Volume_Produced,Total_Sales,Quality_Score,Brewhouse_Efficiency,Loss_During_Brewing,Loss_During_Fermentation,Loss_During_Bottling_Kegging
3200693,Wheat Beer,Indiranagar,13,23.076632,4.529806,1.078251,4.974777,40,1058,13314.669507,6.207507,75.683330,3.278185,3.935690,2.993265
9730362,Ale,Koramangala,17,17.510793,5.007785,1.037773,5.422240,57,1071,11236.473991,7.588667,89.767963,1.524372,1.767640,2.520185
1639371,IPA,Marathahalli,12,21.865758,4.871052,1.070010,4.638740,34,4669,4177.929370,8.328726,78.654590,2.535355,1.142171,2.471034
9688110,Pilsner,Jayanagar,17,22.495394,5.245223,1.042684,5.494606,42,1272,19479.062275,8.429911,73.425151,4.218219,1.111631,3.822408
8612403,Wheat Beer,Electronic City,18,17.744000,4.860081,1.047119,4.597665,42,4898,16378.030752,6.583201,82.171886,4.452254,2.755884,3.114115

In [63]:
dataset.to_csv("bottle_dataset.csv")